# Defaults for image training.

image_size: 256
num_channels: 256
num_res_blocks: 2
learn_sigma: True
class_cond: False
use_checkpoint: False
attention_resolutions: 32,16,8
num_heads: 4
num_heads_upsample: -1
use_scale_shift_norm: True
dropout: 0.0
model_path: /home/2021/hexin/XJ2/Log/openai-2024-07-28-08-53-35-089446/model095000.pt

